spring.application.name=samt
server.servlet.context-path=/samt

#actuator
management.endpoints.web.exposure.include=health,info,env
management.endpoint.health.show-details=always

info.app.name=${spring.application.name}
info.app.version=${project.version}
info.git.branch=${git.branch}
info.git.commit=${git.commit.id.abbrev}


spring.datasource.url=${MYSQL_SATM_CONN}
spring.datasource.username=avnadmin
spring.datasource.password=${SATM_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Optional but recommended (JPA/Hibernate)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
