spring.application.name=samt
server.servlet.context-path=/samt

#actuator
management.endpoints.web.exposure.include=health,info,env

spring.datasource.url=jdbc:mysql://mysql-11672e7b-ashwin-3dd0.d.aivencloud.com:21606/defaultdb?sslMode=REQUIRED
#spring.datasource.username=
#spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Optional but recommended (JPA/Hibernate)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
